### ISSUE TITLE
[TCPSocket class] => withMemoryRebound: Fatal error

### ISSUE THREAD

**Issue by ngtrungt** [envoy/Embassy#103]
XCode 14.0.1
Mac OS Ventura 13.0
Macbook M1 2020

<img width="1031" alt="Screenshot 2022-10-27 at 17 39 42" src="https://user-images.githubusercontent.com/3261396/198263801-220cfcec-812f-4f4b-9dd1-873f1093ccad.png">

**Comment by beckychristensen** [comment]
I think you are experiencing this issue which is resolved in the latest release: https://github.com/envoy/Embassy/issues/101
