### ISSUE TITLE
Swift 2.3 release

### ISSUE THREAD

**Issue by peterprokop** [envoy/Embassy#18]
Guys, can you please create Swift 2.3 release? If you try to install Ambassador ported to 2.3 via Carthage, it complains while building Embassy.

**Comment by victorlin** [comment]
@peterprokop sure, the travis ci build is broken, I am fixing it right now, will release as soon as I saw the green light

**Comment by victorlin** [comment]
hi @peterprokop, I just released with a new v2.0.0 version tag, also pushed to cocoapods. Could you install it from your end to see if it works?

**Comment by fangpenlin** [comment]
We are now on Swift 3, close this outdated issue
