### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by TofPlay** [envoy/Embassy#24]
Below the title please add badges for carthage compatibility, SwiftPM compatibility (not your case), Swift version and platform compatibility like this:

[![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-brightgreen.svg)](https://github.com/Carthage/Carthage) [![SwiftPM compatible](https://img.shields.io/badge/SwiftPM-compatible-brightgreen.svg)](https://github.com/apple/swift-package-manager) ![Swift Version](https://img.shields.io/badge/Swift-3.0-orange.svg) ![Plaform](https://img.shields.io/badge/Platform-macOS|iOS|tvOS|watchOS-lightgrey.svg)

**Comment by fangpenlin** [comment]
fixed
