### ISSUE TITLE
Embedded only or can be use on a backend Linux server with Swift 3?

### ISSUE THREAD

**Issue by TofPlay** [envoy/Embassy#25]
Hi,
Embassy is only design to be embedded in iOS app or can we use it to develop a backend service on Linux with Swift 3?

**Comment by victorlin** [comment]
@TofPlay I am going to make it workable under linux via this PR #26

**Comment by fangpenlin** [comment]
@TofPlay Linux support PR just merged into master, I had a simple example project here

https://github.com/envoy/example-embassy

Please try it out, let me know if you run into any issue.
