### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by Daniel-Xu** [envoy/Embassy#41]
![image](https://user-images.githubusercontent.com/548144/30945763-114379b8-a3ce-11e7-9c4a-2f23baf901ea.png)

The following is our Pod file:

![image](https://user-images.githubusercontent.com/548144/30945781-27e5eeee-a3ce-11e7-88e0-46b8cf4dd032.png)

**Comment by trisco2001** [comment]
I've been hit by this issue as well, @Daniel-Xu. We're trying to use Embassy 3.1 on Xcode 9 on Swift 3.2. We tried switching to Embassy 4, but we aren't ready to move our own code to Swift 4 yet and this had other compilation errors.

**Comment by fangpenlin** [comment]
@Daniel-Xu @trisco2001 sorry for super late replying. We had a new release v3.2.0 a while ago for addressing the issue

https://github.com/envoy/Embassy/releases/tag/v3.2.0
