### ISSUE TITLE
Could you make a v4.0.1 that includes the Linux fix please?

### ISSUE THREAD

**Issue by felix91gr** [envoy/Embassy#42]
So that the fix you made in #35 can be used with SPM. Please :star:

**Comment by fangpenlin** [comment]
@felix91gr I am not super familiar with how Swift package works, does it help by simply adding a `v4.0.1` tag on current master?

**Comment by felix91gr** [comment]
Yup! That should suffice :)

**Comment by fangpenlin** [comment]
@felix91gr I just pushed the new tag, please let me know if it helps

**Comment by felix91gr** [comment]
Wow! So fast :D 

I'll let you know! Thank you ^^

**Comment by felix91gr** [comment]
It worked! SPM is pretty straightforward, it turns out. Kudos to Ankit's team.

Thank you again for your patience (and speed!) :)
