### ISSUE TITLE
Objective C support

### ISSUE THREAD

**Issue by ganjarpanji** [envoy/Embassy#45]
is it possible using emabassy with uitest coded in objective c?

**Comment by fangpenlin** [comment]
hi @ganjarpanji, we don't have plan to support objective c, however, it's not impossible to use Embassy with objc. What I can think of is, you can write a wrapper in Swift, make the class objective c compatible, then you can use them in your objc code.

For example,


```Swift
import Embassy

@objc class EMDefaultHTTPServer {
    /.../
}

@objc class EMSelectorEventLoop {
    /.../
}
```

then in your objc code, you should be able to use it

```objc
#import <MyProject-Swift.h>

- (void) myFunc () {
    EMSelectorEventLoop *eventLoop = [[EMSelectorEventLoop alloc] initWithOptions:@{/*....*/}];
    // ...
}
```

Although this is totally doable, I am not sure if it worth the effort. There are ObjC HTTP libraries out there already, like this

https://github.com/robbiehanson/CocoaHTTPServer

If you really need light weight HTTP server in ObjC, maybe you can try to find other projects.
