### ISSUE TITLE
SelectorEventLoop is never released

### ISSUE THREAD

**Issue by v-lavrentikov** [envoy/Embassy#59]
In the `SelectorEventLoop` initializer you call `setReader()` method with a callback handler. This callback handler retains `self` object reference. Thus `deinit()` method will never be called after releasing `SelectorEventLoop` reference.
To release object it is needed to call `removeReader()` method first. It is public, but it parameter pipeReceiver is a private field. It looks like something went wrong.

**Comment by fangpenlin** [comment]
Hey @v-lavrentikov, thanks for reporting! That's a good caught. Yep, indeed it's creating a reference cycle there, I've already created a PR here #60, will soon merge it and make a new release once the tests pass.
