### ISSUE TITLE
Crashes when reading the body in Release configurations

### ISSUE THREAD

**Issue by ArnaudWurmel** [envoy/Embassy#96]
# Description of the issue

We are using Embassy to mock our internals API for testing purposes and since we are upgrading our environment (Xcode 11.3.1 to Xcode 12.4) we are experiencing some bugs in our tests in release configuration.

After digging into the issue, we cloned the repository and try to run the unit tests in release and it seems that the library's tests are having the same issue as we do, the tests on the body features are crashing in release (``HTTPServerTests.testPostBody()``, ``HTTPServerTests.testPostWithInitialBody()`` for instance).

[``SelectorEventLoop+177``](https://github.com/envoy/Embassy/blob/065b6ce52596bd06b867cfe17fea2c56dcb53b30/Sources/SelectorEventLoop.swift#L177)
![Capture d’écran 2021-04-22 à 14 17 49](https://user-images.githubusercontent.com/17322573/115712814-8a328580-a375-11eb-9076-3909a1a0b3bd.png)

Has anyone experiencing this during the transition to Xcode 12?

# Environment

macOS Big Sur 11.2.3 (intel)
Xcode 12.4 (12D4e)
Embassy 4.1.3

# Reproduction

Run these unit tests in release configuration:
- ``HTTPServerTests.testPostBody()``
- ``HTTPServerTests.testPostWithInitialBody()``

Both tests shall fail.

**Comment by ArnaudWurmel** [comment]
@Goos Sorry for the mention but I couldn't find any maintainer for this project. 

Could you please have a look into this issue ? I proposed a quick-fix in the PR #97, I would happily update it with your recommendations if needed

**Comment by fsafak453** [comment]
I am having the same issue with the XCUITests
